service: social-media-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 512
  timeout: 30
  endpointType: REGIONAL
  iam:
    role: arn:aws:iam::972151653072:role/lambda

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - './dist/**'
    - './node_modules'
    - '!node_modules/**/@types/**'
    - '!node_modules/**/*.d.ts'
    - '!node_modules/**/.yarn-integrity'
    - '!node_modules/**/.bin'
    - '!node_modules/aws-sdk/**'

functions:
  main:
    handler: dist/handler.handler
    events:
      - http:
          method: ANY
          path: /users/
          cors:
            origin: '*'
      - http:
          method: POST
          path: '/users/follow'
          cors:
            origin: '*'
      - http:
          method: ANY
          path: /posts/
          cors:
            origin: '*'
      - http:
          method: ANY
          path: '/posts/{id}'
          cors:
            origin: '*'
      - http:
          method: POST
          path: '/posts/{id}/likes'
          cors:
            origin: '*'
      - http:
          method: POST
          path: '/posts/{id}/comment'
          cors:
            origin: '*'
      - http:
          method: GET
          path: '/posts/search'
          cors:
            origin: '*'
      - http:
          method: GET
          path: '/posts/feeds'
          cors:
            origin: '*'
      - http:
          method: GET
          path: /auth/
          cors:
            origin: '*'
      - http:
          method: POST
          path: '/auth/sign-up'
          cors:
            origin: '*'
      - http:
          method: POST
          path: '/auth/login'
          cors:
            origin: '*'
