service: social-media-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 512
  timeout: 30
  endpointType: REGIONAL
  iam:
    role: arn:aws:iam::972151653072:role/lambda

functions:
  main:
    handler: dist/handler.handler
    events:
      - http:
          method: ANY
          path: /users/
          cors:
            origin: '*'
      - http:
          method: ANY
          path: '/users/{proxy+}'
          cors:
            origin: '*'
      - http:
          method: ANY
          path: /posts/
          cors:
            origin: '*'
      - http:
          method: ANY
          path: '/posts/{proxy+}'
          cors:
            origin: '*'
      - http:
          method: ANY
          path: /auth/
          cors:
            origin: '*'
      - http:
          method: ANY
          path: /auth/{proxy+}
          cors:
            origin: '*'
